//! Page shell assembly for generated diff documents.
//!
//! CSS chunks and interaction scripts are assembled here from their per-concern
//! consts in `css` and `js`.

use super::HtmlTheme;
use super::ThemeOption;
use super::css::{
    BASE_CSS, COLLAPSE_CSS, PRINT_CSS, RESPONSIVE_CSS, THEME_STYLE, TOOLBAR_CSS, WRAP_CSS,
};
use super::js::{COLLAPSE_JS, NAVIGATION_JS, THEME_INIT_JS, THEME_TOGGLE_JS, WRAP_JS};
use html_escape::encode_text;

/// HTML-escape text for safe embedding in generated markup.
pub(super) fn esc(s: &str) -> String {
    encode_text(s).into_owned()
}

pub(super) fn html_document(title: &str, body: &str, theme: ThemeOption) -> String {
    let data_theme = match theme {
        Some(HtmlTheme::Dark) => "dark",
        Some(HtmlTheme::Light) => "light",
        None => "",
    };
    let title = esc(title);
    format!(
        r#"<!DOCTYPE html>
<html lang="en" data-theme="{data_theme}">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
{THEME_STYLE}{BASE_CSS}{TOOLBAR_CSS}{COLLAPSE_CSS}{WRAP_CSS}{PRINT_CSS}{RESPONSIVE_CSS}
</style>
<script>
{THEME_INIT_JS}
</script>
</head>
<body>
<div class="toolbar">
<button id="prev-change" type="button">Prev</button>
<button id="next-change" type="button">Next</button>
<button id="wrap-toggle" type="button">Wrap off</button>
<button id="theme-toggle" type="button">Toggle theme</button>
</div>
{body}
<footer>Generated by <b>rustdiff</b></footer>
<script>
{NAVIGATION_JS}{COLLAPSE_JS}{WRAP_JS}{THEME_TOGGLE_JS}
</script>
</body>
</html>"#
    )
}
