use crate::diff::data::{Diff, OpKind};
use crate::diff::render::unified::group_into_hunks;
use html_escape::encode_text;
use std::fmt::Write as _;

/// HTML color theme for generated diff pages.
#[derive(Debug, Clone, Copy, PartialEq, Eq, clap::ValueEnum)]
pub enum HtmlTheme {
    Dark,
    Light,
}

const DARK_VARS: &str = "--bg:#0d1117; --panel:#161b22; --text:#c9d1d9; --border:#30363d; \
                        --add-bg:#132c18; --del-bg:#2c1515; --add:#56d364; --del:#ff7b72; \
                        --ln:#6e7681; --hunk:#1f6feb; --header:#30363d;";

const LIGHT_VARS: &str = "--bg:#ffffff; --panel:#f6f8fa; --text:#24292f; --border:#d0d7de; \
                         --add-bg:#e6ffec; --del-bg:#ffebe9; --add:#1a7f37; --del:#cf222e; \
                         --ln:#6e7781; --hunk:#0969da; --header:#d0d7de;";

const CSS: &str = r"
* { box-sizing: border-box; }
body { background: var(--bg); color: var(--text); font-family: monospace;
       margin: 0; padding: 2rem; }
h2 { font-size: 1.1rem; margin: 0 0 0.5rem; }
pre { margin: 0; white-space: pre-wrap; overflow-wrap: break-word; }
code { font-family: inherit; }
del, ins { text-decoration: none; }
ins { color: var(--add); background: var(--add-bg); }
del { color: var(--del); background: var(--del-bg); }

.file-head { padding: 0.3rem 0.5rem; color: var(--ln);
             background: var(--panel); border-bottom: 1px solid var(--border); }

table { border-collapse: collapse; width: 100%; }
td { vertical-align: top; padding: 0; }

/* unified / numbered view */
tr.add { background: var(--add-bg); }
tr.del { background: var(--del-bg); }
tr.ctx:nth-child(even) { background: rgba(128,128,128,0.06); }
td.ln { width: 3.2em; color: var(--ln); text-align: right; padding-right: 0.6em;
        user-select: none; white-space: nowrap; }
td.ln.empty { border-right: 1px solid var(--border); }
td.txt { padding-left: 0.5em; }
tr.hunk td { color: var(--hunk); padding: 0.3em 0.5em;
             background: var(--panel); border-top: 1px solid var(--border);
             border-bottom: 1px solid var(--border); }

/* side-by-side view */
.cell { width: 50%; padding: 0.1rem 0.5rem; border: 1px solid var(--border); }
.cell.add { background: var(--add-bg); }
.cell.del { background: var(--del-bg); }
.cell .ln { display: inline-block; width: 3em; text-align: right; color: var(--ln);
            padding-right: 0.8em; user-select: none; }
thead th { text-align: center; color: var(--text); padding: 0.5rem;
           background: var(--panel); border-bottom: 1px solid var(--border); }

footer { text-align: center; color: var(--ln); font-size: 0.85rem;
         padding: 1rem; border-top: 1px solid var(--border); }
";

fn esc(s: &str) -> String {
    encode_text(s).into_owned()
}

fn html_document(title: &str, body: &str, theme: HtmlTheme) -> String {
    let vars = match theme {
        HtmlTheme::Dark => DARK_VARS,
        HtmlTheme::Light => LIGHT_VARS,
    };
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
:root {{ {vars} }}
{CSS}
</style>
</head>
<body>
{body}
<footer>Generated by <b>rustdiff</b></footer>
</body>
</html>"#
    )
}

/// Git-style unified HTML diff: file headers, hunk headers, tinted add/delete
/// rows, and per-row old/new line numbers.
#[must_use]
pub fn render_unified_html(
    diff: &Diff,
    context: usize,
    old_name: &str,
    new_name: &str,
    theme: HtmlTheme,
) -> String {
    let mut body = String::new();
    write!(
        body,
        "<div class=\"file-head\"><code>--- {}</code></div>\n<div class=\"file-head\"><code>+++ {}</code></div>\n",
        esc(old_name),
        esc(new_name)
    )
    .unwrap();
    body.push_str("<table>\n");

    let hunks = group_into_hunks(&diff.ops, context);
    for hunk in hunks {
        writeln!(
            body,
            "<tr class=\"hunk\"><td colspan=\"3\"><pre>@@ -{},{} +{},{} @@</pre></td></tr>",
            hunk.start_a, hunk.len_a, hunk.start_b, hunk.len_b
        )
        .unwrap();
        let mut old_ln = hunk.start_a;
        let mut new_ln = hunk.start_b;
        for op in &hunk.ops {
            let tokens = match op.kind {
                OpKind::Equal | OpKind::Delete => &diff.old_tokens,
                OpKind::Insert => &diff.new_tokens,
            };
            let start = op.start as usize;
            for line in &tokens[start..start + op.len as usize] {
                match op.kind {
                    OpKind::Equal => {
                        writeln!(
                            body,
                            "<tr class=\"ctx\"><td class=\"ln\">{old_ln}</td><td class=\"ln\">{new_ln}</td><td class=\"txt\"><pre>{}</pre></td></tr>",
                            esc(line)
                        )
                        .unwrap();
                        old_ln += 1;
                        new_ln += 1;
                    }
                    OpKind::Delete => {
                        writeln!(
                            body,
                            "<tr class=\"del\"><td class=\"ln\">{old_ln}</td><td class=\"ln empty\"></td><td class=\"txt\"><pre>{}</pre></td></tr>",
                            esc(line)
                        )
                        .unwrap();
                        old_ln += 1;
                    }
                    OpKind::Insert => {
                        writeln!(
                            body,
                            "<tr class=\"add\"><td class=\"ln empty\"></td><td class=\"ln\">{new_ln}</td><td class=\"txt\"><pre>{}</pre></td></tr>",
                            esc(line)
                        )
                        .unwrap();
                        new_ln += 1;
                    }
                }
            }
        }
    }

    body.push_str("</table>\n");
    html_document(&format!("{old_name} \u{2192} {new_name}"), &body, theme)
}

/// Simple numbered listing with tinted add/delete rows.
#[must_use]
pub fn render_numbered_html(diff: &Diff, theme: HtmlTheme) -> String {
    let mut body = String::new();
    body.push_str("<table>\n");
    for (ln, (kind, text)) in diff.edits().into_iter().enumerate() {
        let class = match kind {
            OpKind::Equal => "ctx",
            OpKind::Delete => "del",
            OpKind::Insert => "add",
        };

        writeln!(
            body,
            "<tr class=\"{class}\"><td class=\"ln\">{}</td><td class=\"txt\"><pre>{}</pre></td></tr>",
            ln + 1,
            esc(text)
        )
        .unwrap();
    }
    body.push_str("</table>\n");
    html_document("Diff", &body, theme)
}

/// Side-by-side HTML built from the op stream.
///
/// Adjacent Delete-to-Insert runs are paired into one row; insert-only and
/// delete-only rows leave the opposite cell empty. Alignment is structural,
/// never derived from line content.
#[must_use]
pub fn render_side_by_side_html(
    diff: &Diff,
    old_name: &str,
    new_name: &str,
    theme: HtmlTheme,
) -> String {
    let mut body = String::new();
    writeln!(
        body,
        "<div class=\"file-head\"><code>{} \u{2192} {}</code></div>",
        esc(old_name),
        esc(new_name)
    )
    .unwrap();
    body.push_str("<table>\n<thead><tr><th>Old</th><th>New</th></tr></thead>\n<tbody>\n");

    let mut old_ln = 1;
    let mut new_ln = 1;
    let mut i = 0;
    while i < diff.ops.len() {
        let op = diff.ops[i];
        match op.kind {
            OpKind::Equal => {
                let start = op.start as usize;
                for line in &diff.old_tokens[start..start + op.len as usize] {
                    writeln!(
                        body,
                        "<tr><td class=\"cell ctx\"><span class=\"ln\">{old_ln}</span><pre>{}</pre></td><td class=\"cell ctx\"><span class=\"ln\">{new_ln}</span><pre>{}</pre></td></tr>",
                        esc(line),
                        esc(line)
                    )
                    .unwrap();
                    old_ln += 1;
                    new_ln += 1;
                }
                i += 1;
            }
            OpKind::Delete if i + 1 < diff.ops.len() && diff.ops[i + 1].kind == OpKind::Insert => {
                let del = &diff.ops[i];
                let ins = &diff.ops[i + 1];
                let del_lines =
                    &diff.old_tokens[del.start as usize..(del.start + del.len) as usize];
                let ins_lines =
                    &diff.new_tokens[ins.start as usize..(ins.start + ins.len) as usize];
                for k in 0..del.len.max(ins.len) {
                    let k = k as usize;
                    let left = del_lines.get(k).map(|l| {
                        format!("<span class=\"ln\">{old_ln}</span><pre>{}</pre>", esc(l))
                    });
                    let right = ins_lines.get(k).map(|l| {
                        format!("<span class=\"ln\">{new_ln}</span><pre>{}</pre>", esc(l))
                    });

                    if left.is_some() {
                        old_ln += 1;
                    }
                    if right.is_some() {
                        new_ln += 1;
                    }

                    let left_cell = left.map_or_else(
                        || "<td class=\"cell del\"></td>".to_string(),
                        |h| format!("<td class=\"cell del\">{h}</td>"),
                    );
                    let right_cell = right.map_or_else(
                        || "<td class=\"cell add\"></td>".to_string(),
                        |h| format!("<td class=\"cell add\">{h}</td>"),
                    );
                    writeln!(body, "<tr>{left_cell}{right_cell}</tr>").unwrap();
                }
                i += 2;
            }
            OpKind::Delete => {
                let start = op.start as usize;
                for line in &diff.old_tokens[start..start + op.len as usize] {
                    writeln!(
                        body,
                        "<tr><td class=\"cell del\"><span class=\"ln\">{old_ln}</span><pre>{}</pre></td><td class=\"cell\"></td></tr>",
                        esc(line)
                    )
                    .unwrap();
                    old_ln += 1;
                }
                i += 1;
            }
            OpKind::Insert => {
                let start = op.start as usize;
                for line in &diff.new_tokens[start..start + op.len as usize] {
                    writeln!(
                        body,
                        "<tr><td class=\"cell\"></td><td class=\"cell add\"><span class=\"ln\">{new_ln}</span><pre>{}</pre></td></tr>",
                        esc(line)
                    )
                    .unwrap();
                    new_ln += 1;
                }
                i += 1;
            }
        }
    }

    body.push_str("</tbody>\n</table>\n");
    html_document("Side-by-Side Diff", &body, theme)
}

/// Word-level inline HTML: per-line rows with changed words wrapped in
/// `<del>`/`<ins>`.
#[must_use]
pub fn render_word_html(diff: &Diff, theme: HtmlTheme) -> String {
    let mut body = String::new();
    let mut line = String::new();
    for (kind, text) in diff.edits() {
        match kind {
            OpKind::Equal => line.push_str(&esc(text)),
            OpKind::Delete => write!(line, "<del>{}</del>", esc(text)).unwrap(),
            OpKind::Insert => write!(line, "<ins>{}</ins>", esc(text)).unwrap(),
        }
        if text.ends_with('\n') {
            writeln!(body, "<pre>{line}</pre>").unwrap();
            line.clear();
        }
    }
    if !line.is_empty() {
        writeln!(body, "<pre>{line}</pre>").unwrap();
    }
    html_document("Word Diff", &body, theme)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::diff::data::Op;

    fn diff(ops: Vec<Op>, old: &[&str], new: &[&str]) -> Diff {
        Diff {
            ops,
            old_tokens: old.iter().copied().map(str::to_owned).collect(),
            new_tokens: new.iter().copied().map(str::to_owned).collect(),
        }
    }

    #[test]
    fn test_esc() {
        // html_escape's text mode escapes & < > (quotes are only special in
        // attributes, which we never populate from user data).
        assert_eq!(esc("a<b>&\"'"), "a&lt;b&gt;&amp;\"'");
        assert_eq!(esc("plain"), "plain");
    }

    #[test]
    fn test_unified_empty() {
        let d = diff(vec![], &[], &[]);
        let html = render_unified_html(&d, 3, "old", "new", HtmlTheme::Dark);
        assert!(html.starts_with("<!DOCTYPE html>"));
        assert!(html.contains("--- old"));
        assert!(html.contains("+++ new"));
        assert!(!html.contains("<tr class=\"ctx\""));
    }

    #[test]
    fn test_unified_simple_change() {
        let a = ["a", "b", "c"];
        let b = ["a", "X", "c"];
        let d = diff(
            vec![
                Op::equal(0, 1),
                Op::delete(1, 1),
                Op::insert(1, 1),
                Op::equal(2, 1),
            ],
            &a,
            &b,
        );
        let html = render_unified_html(&d, 3, "o", "n", HtmlTheme::Dark);
        assert!(html.contains("@@ -1,3 +1,3 @@"));
        assert!(html.contains("<tr class=\"del\""), "missing delete row");
        assert!(html.contains("<tr class=\"add\""), "missing add row");
        assert!(html.contains(">b</pre>"), "missing deleted content");
        assert!(html.contains(">X</pre>"), "missing inserted content");
    }

    #[test]
    fn test_unified_escapes_content() {
        let d = diff(vec![Op::insert(0, 1)], &[], &["<script>alert(1)</script>"]);
        let html = render_unified_html(&d, 3, "o", "n", HtmlTheme::Dark);
        assert!(html.contains("&lt;script&gt;"));
        assert!(!html.contains("<script>alert"));
    }

    #[test]
    fn test_unified_delete_run_two_lines() {
        let d = diff(
            vec![Op::delete(0, 2), Op::insert(0, 1)],
            &["x", "y"],
            &["z"],
        );
        let html = render_unified_html(&d, 3, "o", "n", HtmlTheme::Dark);
        assert_eq!(html.matches("class=\"del\"").count(), 2);
        assert!(html.contains(">x</pre>"));
        assert!(html.contains(">y</pre>"));
    }

    #[test]
    fn test_numbered_rows() {
        let d = diff(vec![Op::equal(0, 1), Op::insert(1, 1)], &["a"], &["a", "b"]);
        let html = render_numbered_html(&d, HtmlTheme::Dark);
        assert!(html.contains("<tr class=\"ctx\""));
        assert!(html.contains("<tr class=\"add\""));
    }

    #[test]
    fn test_side_by_side_pairs_replacement() {
        let d = diff(
            vec![
                Op::equal(0, 1),
                Op::delete(1, 1),
                Op::insert(1, 1),
                Op::equal(2, 1),
            ],
            &["a", "b", "c"],
            &["a", "X", "c"],
        );
        let html = render_side_by_side_html(&d, "o", "n", HtmlTheme::Dark);
        // Paired row: both cells present, delete + add.
        assert!(html.contains("<td class=\"cell del\">"));
        assert!(html.contains("<td class=\"cell add\">"));
        // Content without -/+ markers.
        assert!(html.contains(">b</pre>"));
        assert!(html.contains(">X</pre>"));
        assert!(!html.contains(">+"));
    }

    #[test]
    fn test_side_by_side_delete_only() {
        let d = diff(vec![Op::delete(0, 1)], &["b"], &[]);
        let html = render_side_by_side_html(&d, "o", "n", HtmlTheme::Dark);
        assert!(html.contains("<td class=\"cell del\">"));
        assert!(
            html.contains("<td class=\"cell\"></td>"),
            "empty right cell"
        );
    }

    #[test]
    fn test_side_by_side_insert_only() {
        let d = diff(vec![Op::insert(0, 1)], &[], &["X"]);
        let html = render_side_by_side_html(&d, "o", "n", HtmlTheme::Dark);
        assert!(html.contains("<td class=\"cell\"></td>"), "empty left cell");
        assert!(html.contains("<td class=\"cell add\">"));
    }

    #[test]
    fn test_side_by_side_run_mismatch() {
        // Delete run of 2 paired with insert run of 1 → 2 rows; the second
        // row's right cell is empty.
        let d = diff(
            vec![Op::delete(0, 2), Op::insert(0, 1)],
            &["x", "y"],
            &["z"],
        );
        let html = render_side_by_side_html(&d, "o", "n", HtmlTheme::Dark);
        assert_eq!(html.matches("<td class=\"cell del\">").count(), 2);
        assert_eq!(html.matches("<td class=\"cell add\">").count(), 2);
        assert!(html.contains("<td class=\"cell add\"></td>"), "padded cell");
    }

    #[test]
    fn test_side_by_side_content_starting_with_marker() {
        // A content line whose text begins with "-" must render as context.
        let d = diff(
            vec![Op::equal(0, 1), Op::delete(1, 1), Op::insert(1, 1)],
            &["-foo", "b"],
            &["-foo", "X"],
        );
        let html = render_side_by_side_html(&d, "o", "n", HtmlTheme::Dark);
        assert!(
            html.contains("<td class=\"cell ctx\">"),
            "content line classified wrong"
        );
        assert!(html.contains(">-foo</pre>"));
    }

    #[test]
    fn test_word_inline() {
        let d = diff(
            vec![
                Op::equal(0, 1),
                Op::delete(1, 1),
                Op::insert(1, 1),
                Op::equal(2, 1),
            ],
            &["hello ", "world", "\n"],
            &["hello ", "rust", "\n"],
        );
        let html = render_word_html(&d, HtmlTheme::Dark);
        assert!(html.contains("<del>world</del>"));
        assert!(html.contains("<ins>rust</ins>"));
        assert!(html.contains("hello "));
    }

    #[test]
    fn test_light_theme_vars() {
        let d = diff(vec![], &[], &[]);
        let html = render_unified_html(&d, 3, "o", "n", HtmlTheme::Light);
        assert!(html.contains("--bg:#ffffff"), "light background missing");
        let dark = render_unified_html(&d, 3, "o", "n", HtmlTheme::Dark);
        assert!(dark.contains("--bg:#0d1117"), "dark background missing");
    }
}
